/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "finance-demo"

include(
    "kafka-demo",
    "domain",
    "sh-mock"
)
