version: "3"
services:
  rabbit:
    image: 'rabbitmq:3-management'
    container_name: 'rabbit'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password