server:
  port: 8082

spring:
  rabbitmq:
    host: rabbit-external.demo-messaging
    port: 5672
    username: user
    password: password
    virtual-host: /
  cloud:
    stream:
      function:
        definition: sh-events-consumer

      bindings:
        sh-events-consumer-in-0:
          destination: sh.events
          group: finance-rabbit-queue
          binder: rabbit
          consumer:
            concurrency: 2
            max-attempts: 1

      binders:
        rabbit:
          type: rabbit

      rabbit:
        bindings:
          sh-events-consumer-in-0:
            consumer:
              exchange-type: fanout
              declare-exchange: false
              bind-queue: true

  datasource:
    url: "jdbc:postgresql://postgres-external.demo-messaging:5432/finance_rabbit"
    username: "postgres"
    password: "12345"
  liquibase:
    change-log: "classpath:changelog/changelog-master.xml"

  data:
    redis:
      host: redis
      port: 6379

  cache:
    type: redis

feign:
  sh-mock-client:
    base-url: http://sh-mock:8081
  pay-client:
    base-url: http://pay:8084