apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-data
spec:
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce