apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgadmin-data
  labels:
    clustername: local
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /demo-data/pgadmin-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-data
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  volumeName: pgadmin-data