apiVersion: v1
kind: Service
metadata:
  name: rabbit-external
spec:
  selector:
    app: rabbit
  type: LoadBalancer
  ports:
    - port: 5672
      name: tcp
      targetPort: 5672
      nodePort: 30003
    - port: 15672
      name: http
      targetPort: 15672
      nodePort: 30004
