apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-rabbit
  labels:
    app: finance-rabbit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finance-rabbit
  template:
    metadata:
      labels:
        app: finance-rabbit
    spec:
      containers:
        - name: finance-rabbit
          image: localhost:5000/finance-rabbit:0.0.2
          ports:
            - containerPort: 8082
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "750m"